name: Install dependencies
description: Install dependencies for all projects

runs:
  using: 'composite'
  steps:
    - uses: actions/setup-node@v3
      with:
        node-version: 18.16.1

    # https://github.com/actions/cache/blob/main/examples.md#node---yarn
    # https://dev.to/mattpocockuk/how-to-cache-nodemodules-in-github-actions-with-yarn-24eh
    - name: Cache node modules
      id: cache-node-modules
      uses: actions/cache@v3
      with:
        path: 'node_modules'
        key: ${{ runner.os }}-modules-${{ hashFiles('**/yarn.lock') }}

    - name: Install project dependencies if needed.
      if: steps.cache-node-modules.outputs.cache-hit != 'true'
      shell: bash
      run: |
        yarn install --ignore-platform --frozen-lockfile

    - name: Yarn post install if cache hit
      if: steps.cache-node-modules.outputs.cache-hit == 'true'
      shell: bash
      run: |
        yarn postinstall

    - name: Cache Cypress binary
      uses: actions/cache@v3
      with:
        path: ~/.cache/Cypress
        key: ${{ runner.os }}-cypress-${{ hashFiles('**/yarn.lock') }}
        restore-keys: |
          ${{ runner.os }}-cypress-
